apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5  # Number of pods to run
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest  # Simple web server for hello world
        ports:
        - containerPort: 80  # Exposing port 80 for nginx
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world  # Selects pods with app=hello-world label
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Container port
  type: LoadBalancer  # Expose the service externally
